extraction:
  cpp:
    after_prepare: 
      - python report.py 110
  cobol:
    after_prepare: 
      - python report.py 110
  csharp:
    after_prepare: 
      - python report.py 110
  java:
    after_prepare: 
      - python report.py 110
  javascript:
    after_prepare: 
      - python report.py 110
  python:
    after_prepare: 
      - python report.py 110
